### ISSUE TITLE
show users picture

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#11]
pull users Facebook profile picture to us in app

**Comment by codesworth** [comment]
Already implemented

**Comment by jberkey78** [comment]
1) the profile pictures from Facebook are very low quality.  Is there a way to get a higher quality image?
2) my wifes any my own profile picture were not pulled, had just a placeholder icon. I was able to upload an image she was not (could be due to the Storage maybe full)

**Comment by codesworth** [comment]
Will look into that
