### ISSUE TITLE
Create CLIQ - Keyboard 

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#12]
when I type the title of the CLIQ in there is no "DONE" or "OK" button at top of keyboard showing how to exit the type function.  This is not very intuitive as I had to hit "RETURN" or tap on the image section.
![img_7323](https://user-images.githubusercontent.com/13186530/50742533-7a112f00-11da-11e9-8adf-c9de0d182770.PNG)

**Comment by codesworth** [comment]
The return is specifically set to dismiss the keyboard. Suppose we can change the "Return"  text to Done and avoid addition of a toolbar on top of the keyboard. What do you think

**Comment by jberkey78** [comment]
yes I think we need to be more explicit with the feedback directing the user.  "Done" should work great :)
