### ISSUE TITLE
Missing Navigation buttons

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#18]
Navigation arrows are missing when new user opens app and explores.

This happens on the first time the app is launched by a new user.  I will see if I can recreate it by removing app and downloading it again.

**Comment by codesworth** [comment]
Which specific screens has the missing arrows

**Comment by jberkey78** [comment]
all screens with the navigation arrow and clip name

**Comment by codesworth** [comment]
Alright. Will check it out

**Comment by jberkey78** [comment]
I removed my app and reinstalled it but could not recreate it, but a new tester experienced it upon first time use.  Once he closed the app and reopened they appeared.

**Comment by codesworth** [comment]
Okay, I think I have an idea as to why. Will work on it

**Comment by jberkey78** [comment]
this is still an issue for first time launches only.

**Comment by jberkey78** [comment]
I deactivated my account and signed up again and navigation was there.  I think we still need to watch this for first time ever downloads and launches.

**Comment by codesworth** [comment]
FIxed
