### ISSUE TITLE
CLIQ button (RED)

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#19]
The (RED) button should take you to the last active CLIQ you were in.  It does not apply to CLIQs that have archived (expired)

**Comment by codesworth** [comment]
I was under the impression active meant meant not expired. 
So the active in this context refers to the last cliq a member joined?

**Comment by jberkey78** [comment]
(this is a minor issue right now)
Yes so there is "active" which is non-expired CLIQs near me 
and
there is the "active" with most recent user "activity"

I think that if there are multiple "active" CLIQs that a user has joined; the RED button should change based on which "active" CLIQ the user was last in.

**Comment by codesworth** [comment]
Alright... That makes sense. I get it now.

**Comment by jberkey78** [comment]
cool again this is not a high priority, but it is the intended interaction :)

**Comment by codesworth** [comment]
Does the "latest cliq the user was in" include Nearby Cliqs that they have no joined yet ?

**Comment by jberkey78** [comment]
I think just a clip that user has joined

**Comment by jberkey78** [comment]
There might have been a little confusion.  This button should not display for CLIQs that have expired , just if they were in a currently "active" CLIQ.

**Comment by codesworth** [comment]
Okay. So Unarchived cliq that the user was just in.

**Comment by jberkey78** [comment]
yeah, it must still be in it's "24" hour public period...sorry it is confusing haha

**Comment by jberkey78** [comment]
today I tested with a group and the RED button only linked back to old CLIQs and not the new one we created to test in today.

**Comment by codesworth** [comment]
I will push an update to fix this by weekend

**Comment by jberkey78** [comment]
will see if next update fixes the issues, but also noticing that sometimes it appears and other times is is missing...will hold on any further observed behavior until next release.
