### ISSUE TITLE
Location Radius for a CLIQ

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#20]
What is our location radius set to for a CLIQ?  I tested with a group today and when I left I jumped back into the app when I was about 2 miles away and it said I still had a CLIQ near me.  Not sure if it is a device caching thing or the radius.  Something to look into.

**Comment by jberkey78** [comment]
cool, we might want to narrow down to 400 meters if we can.  I think this is a distance @entaq and I had talked about.  Thoughts on this?

**Comment by codesworth** [comment]
400 is okay

**Comment by jberkey78** [comment]
was this implemented in new release?  If so we can close it :)

**Comment by codesworth** [comment]
Yeah Implemented. Although I noticed a bug after this upload which persisted cliqs that were no longer nearby. It has to do with the caching mechanism so that it will be fixed in next update.
