### ISSUE TITLE
Member Limit for Cliq

### ISSUE THREAD

**Issue by codesworth** [entaq/floq#22]
Can we set a maximum capacity limit to the members that can join a cliq. I suggest we set it to 20 for now. What do you think.

**Comment by jberkey78** [comment]
What would the purpose of a limit be?  I am open to it for the time, but if I goto a large venue or event there is a lot of power in letting large groups join.  Also weddings and parties can often be much larger than 20.

**Comment by codesworth** [comment]
The main idea for this is to put database charges in check for now.  We can increase the size as we grow. Maybe we can set to 100 for events. 

Also setting a limit can give us a leverage for in-app purchase to extend it to for some cliqs that will be created by Big events and conferences (Just a thought on monetizing).

Thoughts

**Comment by jberkey78** [comment]
agree that it can help with the database, lets set it at 30 for now.  Realistically we probably won't have any large groups for a while although it is possible.

And yes I have some monetization ideas around special CLIQs and number of users is one of them as well as promoted CLIQs but we are not quite there...but totally agree that could be a good option.

**Comment by codesworth** [comment]
What about the maximum number of photos that can be added to a single cliq. Can we place a cap on that too or we should leave it unlimited for now?

**Comment by jberkey78** [comment]
I think we should leave it as unlimited for now, but it is something to think about.  For this type of app, a lot of users get turned off by in-app purchases so I think if implemented they need to be strategic.  I have ideas around monetization and tiers on my business side of the app.  Right now we just focus on core experience and features :)

**Comment by codesworth** [comment]
Alright
