### ISSUE TITLE
Time a CLIQ is active

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#23]
I am thinking maybe we have CLIQs expire from public view after 12 hours rather than 24.  Thoughts?

**Comment by codesworth** [comment]
I think for a start lets keep it at 24hrs to keep the probability of discovery higher. We an reduce that later.

**Comment by jberkey78** [comment]
ture, most use cases are group or event specific so 24 hours can be a lot, but agree it's not a major issues at the moment.
