### ISSUE TITLE
CLIQ missing from My Cliqs

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#25]
Is there a limit set to how many CLIQs I can have?  I have 10 and I created a new one today that only showed up in "Near Me" and not in "My Cliqs"

**Comment by codesworth** [comment]
There is no limit now. It should refresh and show up in your cliqs. I will check it out. This is probably due to multiple updates called at same time. Will find a better way to handle multiple updates

**Comment by jberkey78** [comment]
Yeah this one is weird because I created the CLIQ "121 Day One" and it does not show up for me in My Cliqs, it only showed up in Near Me.  Then when it expired I couldn't see it at all, but everyone who joined has it.

**Comment by codesworth** [comment]
Have you updated to the latest build version in TestFlight. I checked the cliq in question and it appears to use the old format for saving data. The new format comes with last Testflight build and is optimized to be cost efficient.

**Comment by jberkey78** [comment]
the cliq I created today does not show up in My Cliqs so this is definitely an issue. For me it only showed up in "Near Me" and not "My Cliqs" even though I was the creator.  Cliq name is 121 Rock 'n Roll

**Comment by codesworth** [comment]
I am constantly restructuring the database for optimization and cost efficiency purposes. Once we launch the database will be locked for changes, so sorry for the missing cliqs. They are as a result of the new structuring 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jberkey78** [comment]
awesome...sounds great :)
