### ISSUE TITLE
Picture upload App crash

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#27]
I have been experiencing the app crashing when 

experienced on - CLIQ - 121 Rock 'n Roll

a) taking photo and adding in-app
b) uploading image from camera roll

When I created a cliq, the cover photo was fine and the app did not crash.

**Comment by codesworth** [comment]
I have already come across this too. It's resolved now. No worries 👍

**Comment by jberkey78** [comment]
Cool yeah, some else found a work around for this version, which I validated.  Thats awesome you fixed it for next release:)  

Current work around:
1) take photo outside the app
2) upload the photo from the camera roll
3) now you should be able to take a photo in app
