### ISSUE TITLE
image in clip loading animation

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#29]
radial animations on image loading is overwhelming when there are lots of photos loading.  I like the idea though and will think of something a little more subtle.  Maybe making the thumbnails spaces gray to stand out from the white.  will think about it...thanks :)

**Comment by codesworth** [comment]
Yeah I just threw it out there for convenience. Will be great if u suggested something else from design point of view.

**Comment by codesworth** [comment]
Fixed
