### ISSUE TITLE
Miss “add photo” button

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#30]
The add photo button is now missing from all cliqs

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codesworth** [comment]
Initially we agreed that you can’t add photos to archived cliqs so only active cliqs now will show that add phot button 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jberkey78** [comment]
It s gone on new cliqs, but lets revert to being able to add after the fact. In testing people like that feature especially if the take photos out of the app. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codesworth** [comment]
Okay. Seen it will push a fix tonight 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
