### ISSUE TITLE
Can’t login with Facebook

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#31]
- ![GitHawk Upload by jberkey78](https://i.imgur.com/voIePLe.jpg)

I removed app and reinstalled and it gives this message and does not allow me to sign in

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jberkey78** [comment]
I reverted to 1.4 (8) and still unable to sign in with Facebook 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jberkey78** [comment]
![GitHawk Upload by jberkey78](https://i.imgur.com/ZUlEs37.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codesworth** [comment]
I think this will have to do with Facebook API will look at it and make fixes tonight 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
