### ISSUE TITLE
sign up screens off on iPhone X's

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#33]
seem attached

![img_7542](https://user-images.githubusercontent.com/13186530/53375810-4cb74680-392a-11e9-9c08-1fcc73ffd8ee.PNG)
![img_7543](https://user-images.githubusercontent.com/13186530/53375811-4d4fdd00-392a-11e9-8b05-222009ac30f2.PNG)

**Comment by jberkey78** [comment]
the bottom of the screen is white and the feather should be coming out of the bottom of the screen.  I an provide separate assets if needed

**Comment by jberkey78** [comment]
this seems to still be an issue.

**Comment by codesworth** [comment]
will check it out
