### ISSUE TITLE
Pre App Store Submission checklist

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#35]
- fix onboard screens for iPhone X and larger screens

- add link to Privacy Policy from Profile screen

- remove Terms of Use from Profile screen (will add back in later)

- add App Store images of screens

- others?

**Comment by codesworth** [comment]
Done except for Images. I think we can use screenshots from your app running in the iPhone X screen. I can take some with the simulator but it would be better to get screenshots showing full views full of cliqs and photos.

**Comment by codesworth** [comment]
So I suggest when you get the time to load your app with cliqs and photos and take snapshots of them. We would use those for the appstore submission

**Comment by jberkey78** [comment]
Yeah I did that the other day before I tested account deletion. I found a tool I will try to use, just need some down time when home lol https://theapplaunchpad.com

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
