### ISSUE TITLE
Missing red button

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#36]
Red button that navigates from landing screen to active cliq missing

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codesworth** [comment]
Still unclear on this. Havent been able to replicate on my end. has any of the testers encountered same issue

**Comment by jberkey78** [comment]
Yup, there have been others missing it. I’ll try to confirm today 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
