### ISSUE TITLE
flag images

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#37]
updated design with flag icon in Zeplin.

**Flag this image as abusive or inappropriate?**
By flagging this image it will be removed from the "cliq" and the administrators of the app will review the content and permanently remove any images and users associated with it if found to be agains the End User Agreement.
 BUTTON: left [Cancel] right [Report]

**Comment by jberkey78** [comment]
when a user flags an image it should be removed from the "Cliq".  On the backend we need a repository for those images to be stored along with the user data so we can review to see if the image was indeed abusive or inappropriate. We should also have a mechanism to add the photo back to the album if the image is okay.

**Comment by codesworth** [comment]
We have one more issue with the flagged pictures. The first image of a cliq is always the cover image of the cliq, what happens to the cliq if a user flags the image which is the cover image of that cliq?. For now, that image is removed from the cliq and the cliq photos appears to be empty however the image will still be seen as the cover of the cliq. Any thoughts on how to handle this.

**Comment by jberkey78** [comment]
Yeah good catch. Some options.
A) it defaults to the next photo in the cliq
B) it’s blank and user who created cliq is notified and requested to add new a new cover photo
C) it stays blank

I’ll think about it a lil more too

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codesworth** [comment]
I think when a photo is flagged, it only disappears for the user who flagged it, so what we do is replace the cover with a placeholder image (this case a blank background with the seafoamBlue color of the app). In the event the photo is found to be abusive and we delete it then we can make the next image the cover image for everyone

**Comment by jberkey78** [comment]
Yeah I’m good with that. What’s the status on the web app?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codesworth** [comment]
I have worked on the flagging part. Im trying to add an interface to observe and manage the signed up users and some analytic stuff. i would deploy it by month ending
