### ISSUE TITLE
Cliq count is not correct

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#43]
My Cliqs says I have six, but in reality I have 16. I think it’s only counting from
The last two builds. 

Also I’m thinking now that we’re released we wipe the old cliqs that we’re used in testing. Thoughts?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codesworth** [comment]
Oh yeah I had that in mind. we have to wipe the database and all the registered accounts. the counts feature was introduced later on so the previous cliqs created were exempted. i will do that tonight. Clear all the data

**Comment by jberkey78** [comment]
so anyone who has downloaded it will lose their account?

**Comment by jberkey78** [comment]
I guess that's fine, they will just have to re-sign in / register

**Comment by codesworth** [comment]
Yeah and also clear our storage bucket. SO we can get an accurate count from our analytics after we go live. I will finish by week end so let hold on release till after then

**Comment by jberkey78** [comment]
it's already released, thought I messaged that.  It's fine, not promoting it so only people on it are people who have used TestFlight version.  I doubt it will get any organic traffic without promotion...hard to find ha
