### ISSUE TITLE
empty state message when clip is loading

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#46]
when an cliq is being opened and loading images that have not been loaded already the empty state message appears saying it is empty.  Let's just show a loading animation, something like this.

https://iosexample.com/high-performance-custom-dot-loading-indicator-in-ios/

**Comment by jberkey78** [comment]
it should only have the empty state when the cliq has no images :)

**Comment by jberkey78** [comment]
is this getting addressed?

**Comment by codesworth** [comment]
FIxed
