### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#47]
1) we will get rid of the expanding the image when in comments, this isn't working and is confusing to users.
2) the back button will be the way to navigate, this will also eliminate the animation of the profile picture from the top which is not necessary.  
3) when clicking on comments the user will be able to start commenting immediately, right now there are too many steps to adding a comment two updated designs in Zeplin with comments see one here - zpl.io/awO69kJ
4) no lines between comments

**Comment by codesworth** [comment]
Alright

**Comment by jberkey78** [comment]
visual indication on image there is a new comment - zpl://screen?pid=56aa2ace5695040e063fbdf2&sid=5a372dff1a17248135363cba

**Comment by jberkey78** [comment]
visual indicator on image thumbnail there is a new comment - zpl://screen?sid=5a2f2d16d591a7ac7105d853&pid=56aa2ace5695040e063fbdf2

**Comment by codesworth** [comment]
For No. 4: No lines between cliq works fine for short comments but when long comments are added or comments separated by long spaces the layout of the comment screen doesnt particularly look appealing
![Uploading WhatsApp Image 
![WhatsApp Image 2019-08-19 at 14 08 34](https://user-images.githubusercontent.com/20147629/63272047-e6810000-c28a-11e9-97f9-f7aa31fcf463.jpeg)
2019-08-19 at 14.08.35.jpeg…]()

Added some images. Maybe you could review the UI a bit

**Comment by jberkey78** [comment]
Yeah I get that, fair point. I’m not sure it’ll be used that way.  What’s it look like with a kind in those instances?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
