### ISSUE TITLE
Cliq expires from public view

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#5]
CLIQ's expire from public view and become archived.  I think Arun and I originally thought they would expire at midnight (eventually set a custom time)  Thoughts on this - (a) we add a button to Archive the CLIQ (b) we set a default time 12am (midnight) (c) ??

**Comment by codesworth** [comment]
Currently public cliqs can only be seen by location. So we can filter out all nearby cliqs that have reached 24hr maturity. So we only see active ones.
