### ISSUE TITLE
Incorrect string in create screen

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#59]
After 12 hours it will no longer be discoverable, but will always be accessible in the My Cliqs section. 

![GitHawk Upload by jberkey78](https://i.imgur.com/PY03Wmi.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codesworth** [comment]
This part came as an image in Zeppelin so i copied the image resource from zepellin. You will have to update it from the Zeppelin so i can redownload it

**Comment by jberkey78** [comment]
I updated the string in Zeplin :)
