### ISSUE TITLE
Home Screen

### ISSUE THREAD

**Issue by jberkey78** [entaq/floq#6]
The landing screen will have sections (a) My CLIQs (all my archived albums) (b) Active CLIQS near me (ones I can join) (c) FUTURE we will have STREAMS which are searchable CLIQs through #hashtags

If I am in an active CLIQ there will be a button at top that takes me directly to that one so I don't have to search for it.   zpl.io/bAGljd6

**Comment by codesworth** [comment]
In the event of having multiple active clicks, how does this works

**Comment by codesworth** [comment]
Im assuming an active cliq is a cliq that you either created or joined and hasn't reached it 24hr maturity period right?

**Comment by jberkey78** [comment]
@codesworth yup that is an issue, we are assuming the user is in one active CLIQ but someone could be in multiple.  @entaq and I had talked in the past that if this were the case that it would be the one that the user was in most recently.  I will think about some other options too.
